### ISSUE TITLE
Not functioning as expected (broken README example etc.)

### ISSUE THREAD

**Issue by rayrrr** [Saecki/rust-mp4ameta#1]
Hi @Saecki thank you for your work here! We would like to use this crate in another project, for _reading_ existing atoms/tags on M4A files in a personal music library. See https://github.com/agersant/polaris/pull/82

However, it returns `None` for all atoms/tags. This simplified example based on your README is panicking on the 2nd unwrap:

```
fn main() {
    let tag = mp4ameta::Tag::read_from_path("music.m4a").unwrap();
    println!("{}", tag.artist().unwrap());
}
```

Any information would be helpful.

**Comment by Saecki** [comment]
I can't replicate the behavior you're getting. Are you sure the song is using ITunes style mp4 metadata and not ID3? If so could you provide the file so I check what is going wrong?

**Comment by rayrrr** [comment]
Certainly. The file is here: https://github.com/rayrrr/polaris/blob/master/test/sample.m4a

[AtomicParsley](http://atomicparsley.sourceforge.net) is finding the atoms of this file correctly on the command line with this output:

```
> AtomicParsley sample.m4a -t
Atom "©nam" contains: TEST TITLE
Atom "©ART" contains: TEST ARTIST
Atom "aART" contains: TEST ALBUM ARTIST
Atom "©alb" contains: TEST ALBUM
Atom "©day" contains: 2016
Atom "©too" contains: Lavf58.29.100
Atom "trkn" contains: 1
Atom "disk" contains: 3

```

However when replacing `music.m4a` with `sample.m4a` in the modified example as posted in description above, I get a panic on the 2nd unwrap which I understand to mean that it did in fact find the file but is unable to retrieve this metadata. Please advise. Thank you.

**Comment by Saecki** [comment]
Thank you for reporting this. There certainly seems to be a bug. I will look into this.

**Comment by Saecki** [comment]
I pushed what I believe is the fix for this. On my end the file is now being parsed successfully .

**Comment by rayrrr** [comment]
Thank you so much for the quick response @Saecki. I have confirmed that the example described above now returns `TEST ARTIST` as expected! Would you mind bumping the crate version and publishing to crates.io so we don't have to use a git dependency in our Cargo.toml?

**Comment by Saecki** [comment]
Done
