### ISSUE TITLE
Access read-only audio properties

### ISSUE THREAD

**Issue by uklotzde** [Saecki/rust-mp4ameta#13]
For accessing the following read-only properties I need to read the file twice using the [mp4 crate](https://crates.io/crates/mp4):

- [Channel config](https://docs.rs/mp4/0.7.2/mp4/struct.Mp4Track.html#method.channel_config)
- [Sample rate](https://docs.rs/mp4/0.7.2/mp4/struct.Mp4Track.html?search=#method.sample_freq_index)
- [Bitrate](https://docs.rs/mp4/0.7.2/mp4/struct.Mp4Track.html#method.bitrate)

Would it be possible to provide them for consistency and completeness?

**Comment by Saecki** [comment]
That should be possible.

**Comment by Saecki** [comment]
So i finally got around implementing this. If this fits your needs I would publish a new release.

**Comment by uklotzde** [comment]
Great to hear, thank you! Will try this soon and report back.

**Comment by uklotzde** [comment]
I suggest to return std::time::Duration instead of f64 seconds.

**Comment by uklotzde** [comment]
Removed mp4 in favor of mp4ameta: https://gitlab.com/uklotzde/aoide-rs/-/commit/3f326ae9a2fad0cabf2c987c9f94a21e4da1597a

Another idea I just discovered in an embedded crate: How about using `Hz44100` instead of `F44100` for the sample rate frequencies? This would be explicit, readable, and concise.

**Comment by Saecki** [comment]
Using explicit `std::time::Duration` and `Hz` definitely sounds good. I just fixed a bug with parsing descriptors and now all songs in my library are successfully parsed, however I still need to clean things up. After that and your suggested changes we should be good to go.

**Comment by Saecki** [comment]
I just published version `0.9.0`.
