### ISSUE TITLE
Sample rate: Use u32 instead of usize

### ISSUE THREAD

**Issue by uklotzde** [Saecki/rust-mp4ameta#16]
The type of the sample rate depends on the range of possible values, but neither on the platform nor the CPU architecture. The return type `usize` for `SampleRate::hz()` is not a good match. Using `u32` with a known size would be a better choice.

**Comment by Saecki** [comment]
Seems reasonable.

**Comment by Saecki** [comment]
[Done](https://github.com/Saecki/rust-mp4ameta/commit/2dd6fb797fae30dd7bde8186f3b2bc7d4a871313)
