### ISSUE TITLE
Q: Can `©day` only include year?

### ISSUE THREAD

**Issue by probablykasper** [Saecki/rust-mp4ameta#21]
Hey, got a question about the `©day` tag. Feel free to close if you don't know or want to answer.

In most places, it looks like `©day` is just mentioned as being for the year. However, it's of course named `©day` and the [Movie Atoms](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html) specification describes `©day` as `Date the movie content was created`.

Is it valid to enter info like month/date/time in `©day`, and if so, what format?

ID3v2.4's `TDRC` tag lets you optionally include month, date and time in the format `yyyy-MM-ddTHH:mm:ss`.

**Comment by Saecki** [comment]
Yes `©day` can contain any string, there is no exact spec that I know of. I think what format to use depends on what music player etc. you use.

**Comment by probablykasper** [comment]
Makes sense, thanks for letting me know! I'll have to decide on a format
