### ISSUE TITLE
How to set back cover?

### ISSUE THREAD

**Issue by evensolberg** [Saecki/rust-mp4ameta#24]
First, thanks for making this crate!

I can set the artwork(s) using the various `set_artwork` functions, but there doesn't appear to be any way to identify whether I'm setting a front cover, back cover, etc? Am I missing something here? Can it be done?

**Comment by Saecki** [comment]
Currently there is no support for that and I don't think there is a spec for that. If you know of some other program that has support, let me know.

**Comment by evensolberg** [comment]
The one I use lets me select what it is when I add an image, but if I save and load back, it just tags it as "Other", so I guess not. Oh well. I'll just live without. Thanks.

Side question: Is there an easy way to create a `Fourcc` tag from a string containing (say) the `aART` ... How do I turn that into `Fourcc(*b"aART")`?

**Comment by Saecki** [comment]
Something along the lines of `. as_bytes().try_into()` should work, to turn the string into a byte array. I don't think there is a non fallible way.

**Comment by evensolberg** [comment]
It compiles but crashes out at runtime with "could not convert slice to array". Might be useful to have a `Fourcc::from(&str)` as a future enhancement ...
