### ISSUE TITLE
`Data already parsed` error

### ISSUE THREAD

**Issue by agersant** [Saecki/rust-mp4ameta#6]
I'm seeing a few errors like the one below when scanning my music collection in Polaris. I attached an example file causing the issue. [bad.zip](https://github.com/Saecki/rust-mp4ameta/files/5236514/bad.zip)

```
Parsing: Error reading moov: Error reading udta: Error reading meta: Error reading ilst: Error reading ©ART: Error reading data: Data already parsed
```
I am also getting a few of these, even though foobar2000 can show metadata for these files just fine:

```
NoTag: File does not contain MPEG-4 audio metadata
```

**Comment by Saecki** [comment]
Thank you for reporting this.
The error occurs when multiple atoms of one type, in this case the `©ART` (Artist), are present. This is a flaw that I didn't think of in the initial design, but I am currently rewriting the way data is parsed to be more flexible and support multiple atoms of one type.

**Comment by Saecki** [comment]
The first error should be fixed with the commit I pushed on the dev branch. Documentation and full support for accessing multiple values of one atom type are still missing though.

**Comment by agersant** [comment]
Thank you!

**Comment by Saecki** [comment]
Version `0.4.0` containing the changes is now published.
